version: "3.5"

services:
  lulztech-landing:
    image: registry.ci.lulztech.ml/lulztech_landing
    container_name: lulztech-landing
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`lulztech.ml`)"
      - "traefik.http.routers.portainer.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.portainer.entrypoints=websecure"

networks:
  default:
    external:
      name: traefik
